/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package firenze.project.tiny.spring;

import com.thoughtworks.fusheng.integration.junit5.FuShengTest;
import firenze.project.tiny.spring.di.container.ContainerConfig;
import firenze.project.tiny.spring.di.container.FDIContainer;
import firenze.project.tiny.spring.example.*;

@FuShengTest
public class FDISpeTest {
    private FDIContainer container;
    public void initContainer() {
        ContainerConfig containerConfig = new MockContainerConfig();
        container = new FDIContainer(containerConfig);
    }

    public String getEngineName() {
        return container.get(Engine.class).getName();
    }

    public String getCarName() {
        return container.get(FieldInjectedCar.class).getName();
    }

    public String getCarEngineName() {
        return container.get(FieldInjectedCar.class).getEngine().getName();
    }

    public String getConstructorInjectedCarName() {
        return container.get(ConstructorInjectedCar.class).getName();
    }

    public String getConstructorInjectedCarEngineName() {
        return container.get(ConstructorInjectedCar.class).getEngine().getName();
    }

    public String getNamedEngineCarName() {
        return container.get(Car.class).getName();
    }

    public String getNamedEngineCarEngineName() {
        return container.get(Car.class).getEngine().getName();
    }
}
